services:
    database:
        image: mysql:5.7
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: "escopar"
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - "3306:3306"
        volumes:
            - "./.mysql-data/db:/var/lib/mysql"
